services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn p3_comproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
